"""empty message

Revision ID: aa10153f2cbd
Revises: 
Create Date: 2022-02-19 14:22:09.727926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa10153f2cbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=155), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('budgets',
    sa.Column('budget_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('budget_name', sa.String(), nullable=False),
    sa.Column('budget_description', sa.String(), nullable=False),
    sa.Column('budget_amount', sa.Integer(), nullable=False),
    sa.Column('budget_frequency', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('budget_id'),
    sa.UniqueConstraint('budget_name')
    )
    op.create_table('advice',
    sa.Column('advice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advice_name', sa.String(), nullable=False),
    sa.Column('advice_description', sa.String(), nullable=False),
    sa.Column('advice_price', sa.Integer(), nullable=False),
    sa.Column('advice_img', sa.String(), nullable=True),
    sa.Column('advice_info_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.budget_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('advice_id'),
    sa.UniqueConstraint('advice_name')
    )
    op.create_table('user_transactions',
    sa.Column('user_transactions_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_transactions_name', sa.String(), nullable=False),
    sa.Column('user_transactions_amount', sa.Integer(), nullable=False),
    sa.Column('user_transactions_date', sa.Date(), nullable=True),
    sa.Column('user_transactions_processed', sa.Boolean(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.budget_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_transactions_id'),
    sa.UniqueConstraint('user_transactions_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_transactions')
    op.drop_table('advice')
    op.drop_table('budgets')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
